version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Intro-to-SE-lab-Spring-22/Group-2/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: cimg/node:16.14.2
jobs:
  test-job:
    executor: my-custom-executor
    steps:
      - checkout:
          working_directory: ~/web-files
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_WORKING_DIRECTORY
      - run:
          name: "Check files in this directory"
          command: ls -a
      - run:
          name: "Move into web-files directory"
          command: cd web-files/
      - run:
          name: "Sanity check that it's actually in the right directory"
          command: ls -a
      - run:
          name: "Please actually run the tests"
          command: yarn test
        
workflows:
  my-custom-workflow:
    jobs:
      - test-job