version: 2.1

orbs:
  node: circleci/node@4.7.0

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Intro-to-SE-lab-Spring-22/Group-2/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  test-job:

    executor: my-custom-executor
    steps:
      - checkout
      - run: yarn test

workflows:
  my-custom-workflow:
    jobs:
      - test-job
