version: 2.1

orbs:
  node: circleci/node@2.1.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Intro-to-SE-lab-Spring-22/Group-2/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: cimg/node:16.14.2
        
jobs:
  test-job:

    executor: my-custom-executor
    steps:
      - checkout
      - node/install:
          install-npm: false
          node-version: 12.16.2
      - node/install-yarn:
          version: 1.22.4
      - run: yarn --version
      - run: yarn test

workflows:
  my-custom-workflow:
    jobs:
      - test-job
