version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Intro-to-SE-lab-Spring-22/Group-2/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: circleci/node:16.14.2
        
jobs:
  test-job:

    executor: my-custom-executor
    steps:
      - checkout
      - run: npm install
      - run: npm install yarn
      - run: yarn run test

workflows:
  my-custom-workflow:
    jobs:
      - test-job
