version: 2.1

orbs:
  node: circleci/node@4.7.0

executors:
  my-custom-executor:
    docker:
      - image: cimg/node:17.9.0
jobs:
  test-job:

    executor: my-custom-executor
    steps:
      - checkout
      - run: yarn test

workflows:
  my-custom-workflow:
    jobs:
      - test-job
