version: 2
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    working_directory: ~/web-files
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Intro-to-SE-lab-Spring-22/Group-2/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run: yarn test